### PR TITLE
UI fixes & improvements

### LINKED ISSUE #165: Scrolling changes the value of numeric input fields
https://user-images.githubusercontent.com/1579899/158656267-222fb867-7993-4cb4-8512-5ce8701df603.mp4

### LINKED ISSUE #167: Offline mode icon disappears when going into account creation
https://user-images.githubusercontent.com/547923/158667017-4be75f7b-0730-4089-8819-65781681538f.mp4

### PR DESCRIPTION
**Pull request by mvaivre**
Fixes #165, #167 and #168

### CODE REVIEW

File: src/components/Inputs/Toggle.tsx [hunk 1]
```diff
@@ -17,31 +17,44 @@ along with the library. If not, see <http://www.gnu.org/licenses/>.
...
   }
 
+  const handleVariants = {
+    off: { backgroundColor: handleColors?.[0] ?? 'var(--color-white)' },
+    on: { backgroundColor: handleColors?.[1] ?? 'var(--color-white)' }
+  }
+
+  useEffect(() => {
+    setToggleWidth(parseInt(getComputedStyle(document.documentElement).getPropertyValue('--toggleWidth')))
+  }, [])
```
Comment (lf94) [inline src/components/Inputs/Toggle.tsx:56]: If my `useEffect` intuition is correct, this will only ever fire once since the dependency list is empty? Intended or should it be omitted?

**Review by lf94 — COMMENTED** [review]
Perfecto :ok_hand:

File: src/components/Inputs/Toggle.tsx (hunk 1 above)
Comment (mvaivre) [reply src/components/Inputs/Toggle.tsx:56]: Yes! I want this to be ran on first render only 👍

**Review by lf94 — APPROVED** [review]

File: src/components/Inputs/Input.tsx [hunk 2]
```diff
@@ -57,6 +62,7 @@ const Input = ({ placeholder, error, isValid, disabled, onChange, value, ...prop
         className={className}
         disabled={disabled}
         isValid={isValid}
+        onWheel={handleScroll}
```
Comment (lf94) [inline src/components/Inputs/Input.tsx:65]: I was originally going to do this, and what made me think this was non-trivial was that we have to consider if *all* `number` inputs should have the scroll wheel behavior disabled / overridden.

IMO it's fine to override all their behavior, it's just something to consider for the future.

**Review by lf94 — APPROVED** [review]

File: src/components/Inputs/Input.tsx (hunk 2 above)
Comment (mvaivre) [reply src/components/Inputs/Input.tsx:65]: Yes, for now I also believe that it's a good / safe compromise.

File: src/components/AppHeader.tsx [hunk 3]
```diff
@@ -134,4 +142,9 @@ const HeaderContainer = styled(motion.header)`
   }
 `
 
+const OfflineIcon = styled(WifiOff)`
+  color: ${({ theme }) => theme.font.secondary};
+  margin: 0 10px !important;
```
Comment (nop33) [inline src/components/AppHeader.tsx:147]: Everything seems to work fine without the `!important` as well, so let's avoid it when it's not needed.

**Review by nop33 — APPROVED** [review]
